dataset: Data/raw.csv

preprocessing:
  drop_columns: ["index", "flight"]
  scale: true
  encode: true
  impute:
    duration: median
    days_left: median
    price: median

model:
  type: RandomForestRegressor

  params:
    n_estimators: 200
    max_depth: 20
    random_state: 42

training:
  test_size: 0.2
  random_state: 42

preprocessing:
  log_target: true